var bdestadociudad=`
ESTADO,ESTADO-valor,CIUDAD,CIUDAD-valor,TARIFA
Aguascalientes,aguascalientes,Aguascalientes,aguascalientes,PDBT
Aguascalientes,aguascalientes,Cruz de Huanacaxtle,cruz de huanacaxtle,DAC
Aguascalientes,aguascalientes,San Francisco de los Romo,san francisco de los romo,1
Aguascalientes,aguascalientes,Villa de Almoloya de Juárez,villa de almoloya de juarez,1A
Baja California,baja california,El Sauzal,el sauzal,1B
Baja California,baja california,Ensenada,ensenada,1C
Baja California,baja california,Mexicali,mexicali,1D
Baja California,baja california,Playas de Tijuana,playas de tijuana,1F
Baja California,baja california,Rosarito,rosarito,
Baja California,baja california,Tecate,tecate,
Baja California,baja california,Tijuana,tijuana,
Baja California Sur,baja california sur,Cabo San Lucas,cabo san lucas,
Baja California Sur,baja california sur,Ciudad Constitución,ciudad constitucion,
Baja California Sur,baja california sur,Ciudad Insurgentes,ciudad insurgentes,
Baja California Sur,baja california sur,El Pescadero,el pescadero,
Baja California Sur,baja california sur,Guerrero Negro,guerrero negro,
Baja California Sur,baja california sur,La Paz,la paz,
Baja California Sur,baja california sur,La Ribera,la ribera,
Baja California Sur,baja california sur,Loreto,loreto,
Baja California Sur,baja california sur,Los Barriles,los barriles,
Baja California Sur,baja california sur,Mulegue,mulegue,
Baja California Sur,baja california sur,San Jose del Cabo,san jose del cabo,
Baja California Sur,baja california sur,Santa Rosalia,santa rosalia,
Baja California Sur,baja california sur,Todos Santos,todos santos,
Campeche,campeche,Campeche,campeche,
Campeche,campeche,Ciudad del Carmen,ciudad del carmen,
Chiapas,chiapas,Acacoyagua,acacoyagua,
Chiapas,chiapas,Acapetahua,acapetahua,
Chiapas,chiapas,Arriaga,arriaga,
Chiapas,chiapas,Cintalapa de Figueroa,cintalapa de figueroa,
Chiapas,chiapas,Comitán de Domínguez,comitan de dominguez,
Chiapas,chiapas,Escuintla,escuintla,
Chiapas,chiapas,Frontera,frontera comalapa,
Chiapas,chiapas,Frontera Comalapa,frontera hidalgo,
Chiapas,chiapas,Huehuetan,huehuetan,
Chiapas,chiapas,Huixtla,huixtla,
Chiapas,chiapas,Mapastepec,mapastepec,
Chiapas,chiapas,Mazatán,mazatan,
Chiapas,chiapas,Motozintla,motozintla,
Chiapas,chiapas,Ocozocoautla de Espinosa,ocozocoautla de espinosa,
Chiapas,chiapas,Palenque,palenque,
Chiapas,chiapas,Pichucalco,pichucalco,
Chiapas,chiapas,Pijijiapan,pijijiapan,
Chiapas,chiapas,Reforma,reforma,
Chiapas,chiapas,San Cristobal de las Casas,san cristobal de las casas,
Chiapas,chiapas,Suchiate,suchiate,
Chiapas,chiapas,Tapachula,tapachula,
Chiapas,chiapas,Tonalá,tonala,
Chiapas,chiapas,Tuxtla Chico,tuxtla chico,
Chiapas,chiapas,Tuxtla Gutierrez,tuxtla gutierrez,
Chiapas,chiapas,Villa Comaltitlán,villa comaltitlan,
Chihuahua,chihuahua,Aldama,aldama,
Chihuahua,chihuahua,Álvaro Obregón,alvaro obregon,
Chihuahua,chihuahua,Ascensión,ascension,
Chihuahua,chihuahua,Bachíniva,bachiniva,
Chihuahua,chihuahua,Buenaventura,buenaventura,
Chihuahua,chihuahua,Carichí,carichi,
Chihuahua,chihuahua,Chihuahua,chihuahua,
Chihuahua,chihuahua,Ciudad de Camargo,ciudad de camargo,
Chihuahua,chihuahua,Col. Anáhuac,col anahuac,
Chihuahua,chihuahua,Cuauhtemoc,cuauhtemoc,
Chihuahua,chihuahua,Cumuatillo,cumuatillo,
Chihuahua,chihuahua,Delicias,delicias,
Chihuahua,chihuahua,Flores Magón,flores magon,
Chihuahua,chihuahua,Galeana,galeana,
Chihuahua,chihuahua,General Trias,general trias,
Chihuahua,chihuahua,Gómez Farías,gomez farias,
Chihuahua,chihuahua,Guachochi,guachochi,
Chihuahua,chihuahua,Janos,janos,
Chihuahua,chihuahua,Jimenez,jimenez,
Chihuahua,chihuahua,Juarez,juarez,
Chihuahua,chihuahua,La Junta,la junta,
Chihuahua,chihuahua,Madera,madera,
Chihuahua,chihuahua,Matachi,matachi,
Chihuahua,chihuahua,Meoqui,meoqui,
Chihuahua,chihuahua,Namiquipa,namiquipa,
Chihuahua,chihuahua,Norogachi,norogachi,
Chihuahua,chihuahua,Nuevo Casas Grandes,nuevo casas grandes,
Chihuahua,chihuahua,Octaviano Lopez,octaviano lopez,
Chihuahua,chihuahua,Ojinaga,ojinaga,
Chihuahua,chihuahua,Parral,parral,
Chihuahua,chihuahua,Pascual Orozco,pascual orozco,
Chihuahua,chihuahua,Rosales,rosales,
Chihuahua,chihuahua,San Rafael,san rafael,
Chihuahua,chihuahua,Santa Lucia,santa. lucia,
Chihuahua,chihuahua,Saucillo,saucillo,
Chihuahua,chihuahua,Valle de Ignacio Allende,valle de ignacio allende,
Chihuahua,chihuahua,Valle de Zaragoza,valle de zaragoza,
Ciudad de México,cdmx,Ciudad de México - Centro,ciudad de mexico - centro,
Ciudad de México,cdmx,Ciudad de México - Norte,ciudad de mexico - norte,
Ciudad de México,cdmx,Ciudad de México - Sur,ciudad de mexico - sur,
Ciudad de México,cdmx,Distrito Federal,distrito federal,
Ciudad de México,cdmx,Iztapalapa,iztapalapa,
Ciudad de México,cdmx,Miguel Hidalgo,miguel hidalgo,
Coahuila,coahuila,Allende,allende,
Coahuila,coahuila,Arteaga,arteaga,
Coahuila,coahuila,Castaños,castanos,
Coahuila,coahuila,Ciudad Acuña,ciudad acuna,
Coahuila,coahuila,Cuatrocienegas,cuatrocienegas,
Coahuila,coahuila,Francisco I. Madero,francisco i. madero,
Coahuila,coahuila,Frontera Hidalgo,frontera,
Coahuila,coahuila,Lamadrid,lamadrid,
Coahuila,coahuila,Matamoros,matamoros,
Coahuila,coahuila,Monclova,monclova,
Coahuila,coahuila,Morelos,morelos,
Coahuila,coahuila,Muzquiz,muzquiz,
Coahuila,coahuila,Nava,nava,
Coahuila,coahuila,Nueva Rosita,nueva rosita,
Coahuila,coahuila,Ocampo,ocampo,
Coahuila,coahuila,Ocho de Enero,ocho de enero,
Coahuila,coahuila,Parras de la Fuente,parras de la fuente,
Coahuila,coahuila,Piedras Negras,piedras negras,
Coahuila,coahuila,Ramos Arizpe,ramos arizpe,
Coahuila,coahuila,Sabinas Hidalgo,sabinas,
Coahuila,coahuila,Saltillo,saltillo,
Coahuila,coahuila,San Buenaventura,san buenaventura,
Coahuila,coahuila,San Pedro de las Colonias,san pedro de las colonias,
Coahuila,coahuila,Torreon,torreon,
Coahuila,coahuila,Viesca,viesca,
Coahuila,coahuila,Villa Unión,villa union,
Coahuila,coahuila,Zaragoza,zaragoza,
Colima,colima,Cerro de Ortega,cerro de ortega,
Colima,colima,Colima,colima,
Colima,colima,Manzanillo,manzanillo,
Colima,colima,Salagua,salagua,
Colima,colima,Tecomán,tecoman,
Colima,colima,Villa de Álvarez,villa de alvarez,
Durango,durango,Bermejillo,bermejillo,
Durango,durango,Ciudad Lerdo,ciudad lerdo,
Durango,durango,Cuencame,cuencame,
Durango,durango,Durango,durango,
Durango,durango,El Salto,el salto,
Durango,durango,Gómez Palacio,gomez palacio,
Durango,durango,Guadalupe Victoria,guadalupe victoria,
Durango,durango,Nombre de Dios,nombre de dios,
Durango,durango,Nuevo Ideal,nuevo ideal,
Durango,durango,San Jose de la Parrilla,san jose de la parrilla,
Durango,durango,San Juan del Rio,san juan del rio,
Durango,durango,Santa Maria del Oro,santa maria del oro,
Durango,durango,Santiago Papasquiaro,santiago papasquiaro,
Durango,durango,Tlahualilo,tlahualilo,
Durango,durango,Vicente Guerrero,vicente guerrero,
Durango,durango,Victoria de Durango,victoria de durango,
Estado de México,estado de mexico,Aculco,aculco,
Estado de México,estado de mexico,Atizapán de Zaragoza,atizapan de zaragoza,
Estado de México,estado de mexico,Atlacomulco,atlacomulco,
Estado de México,estado de mexico,Atlautla,atlautla,
Estado de México,estado de mexico,Calimaya,calimaya,
Estado de México,estado de mexico,Chalco,chalco,
Estado de México,estado de mexico,Chiconcuac,chiconcuac,
Estado de México,estado de mexico,Cuautitan Izcalli,cuautitan izcalli,
Estado de México,estado de mexico,Ecatepec,ecatepec,
Estado de México,estado de mexico,Huehuetoca,huehuetoca,
Estado de México,estado de mexico,Huixquilucan,huixquilucan,
Estado de México,estado de mexico,Ixtapaluca,ixtapaluca,
Estado de México,estado de mexico,Ixtapan de la Sal,ixtapan de la sal,
Estado de México,estado de mexico,Ixtlahuaca,ixtlahuaca,
Estado de México,estado de mexico,Jilotepec,jilotepec,
Estado de México,estado de mexico,Jocotitlan,jocotitlan,
Estado de México,estado de mexico,Las Delicias,las delicias,
Estado de México,estado de mexico,Malinalco,malinalco,
Estado de México,estado de mexico,Metepec,metepec,
Estado de México,estado de mexico,Naucalpan,naucalpan,
Estado de México,estado de mexico,Nezahualcoyotl,nezahualcoyotl,
Estado de México,estado de mexico,Nicolas Romero,nicolas romero,
Estado de México,estado de mexico,Ojo de Agua,ojo de agua,
Estado de México,estado de mexico,Otzolotepec,otzolotepec,
Estado de México,estado de mexico,Popo Park,popo park,
Estado de México,estado de mexico,Poxtla,poxtla,
Estado de México,estado de mexico,San Andres Ocotlan,san andres ocotlan,
Estado de México,estado de mexico,San Mateo Otzacatipan,san mateo otzacatipan,
Estado de México,estado de mexico,Santiago Teyahualco,santiago teyahualco,
Estado de México,estado de mexico,Santiago Tianguistenco,santiago tianguistenco,
Estado de México,estado de mexico,Tecamac,tecamac,
Estado de México,estado de mexico,Tejupilco,tejupilco,
Estado de México,estado de mexico,Tepotzotlán,tepotzotlan,
Estado de México,estado de mexico,Texcoco,texcoco,
Estado de México,estado de mexico,Tlalmanalco de Velazquez,tlalmanalco de velazquez,
Estado de México,estado de mexico,Tlalnepantla,tlalnepantla,
Estado de México,estado de mexico,Tlalpan,tlalpan,
Estado de México,estado de mexico,Toluca,toluca,
Estado de México,estado de mexico,Tultitlan,tultitlan,
Estado de México,estado de mexico,Valle de Bravo,valle de bravo,
Estado de México,estado de mexico,Valle de Chalco Solidaridad,valle de chalco solidaridad,
Estado de México,estado de mexico,Villa del Carbón,villa del carbon,
Estado de México,estado de mexico,Villa Guerrero,villa guerrero,
Estado de México,estado de mexico,Villa Victoria,villa victoria,
Estado de México,estado de mexico,Xonacatlán,xonacatlan,
Estado de México,estado de mexico,Zumpango,zumpango,
Guanajuato,guanajuato,Abasolo,abasolo,
Guanajuato,guanajuato,Acámbaro,acambaro,
Guanajuato,guanajuato,Celaya,celaya,
Guanajuato,guanajuato,Chupícuaro,chupicuaro,
Guanajuato,guanajuato,Comonfort,comonfort,
Guanajuato,guanajuato,Coroneo,coroneo,
Guanajuato,guanajuato,Cortazar,cortazar,
Guanajuato,guanajuato,Cueramaro,cueramaro,
Guanajuato,guanajuato,Doctor Mora,doctor mora,
Guanajuato,guanajuato,Dolores Hidalgo,dolores hidalgo,
Guanajuato,guanajuato,Guanajuato,guanajuato,
Guanajuato,guanajuato,Huanimaro,huanimaro,
Guanajuato,guanajuato,Irapuato,irapuato,
Guanajuato,guanajuato,Leon,leon,
Guanajuato,guanajuato,Moroleon,moroleon,
Guanajuato,guanajuato,Penjamo,penjamo,
Guanajuato,guanajuato,Presa Blanca,presa blanca,
Guanajuato,guanajuato,Pueblo Nuevo,pueblo nuevo,
Guanajuato,guanajuato,Purisima del Rincon,purisima del rincon,
Guanajuato,guanajuato,Romita,romita,
Guanajuato,guanajuato,Salamanca,salamanca,
Guanajuato,guanajuato,Salvatierra,salvatierra,
Guanajuato,guanajuato,San Felipe,san felipe,
Guanajuato,guanajuato,San Francisco del Rincon,san francisco del rincon,
Guanajuato,guanajuato,San Jose Iturbide,san jose iturbide,
Guanajuato,guanajuato,San Luis de la Paz,san luis de la paz,
Guanajuato,guanajuato,San Miguel de Allende,san miguel de allende,
Guanajuato,guanajuato,Santa Ana,santa ana pacueco,
Guanajuato,guanajuato,Santa Cruz de Juventino Rosas,santa cruz de juventino rosas,
Guanajuato,guanajuato,Santiago Maravatio,santiago maravatio,
Guanajuato,guanajuato,Silao,silao,
Guanajuato,guanajuato,Uriangato,uriangato,
Guanajuato,guanajuato,Valle de Santiago-Bajío,valle de santiago- bajio,
Guanajuato,guanajuato,Valle de Santiago-Centro Occidente,valle de santiago-centro occidente,
Guanajuato,guanajuato,Yuriria,yuriria,
Guerrero,guerrero,Acapulco,acapulco,
Guerrero,guerrero,Atoyac,atoyac de alvarez,
Guerrero,guerrero,Cd. Altamirano,cd altamirano,
Guerrero,guerrero,Chilpancingo de los Bravo,chilpancingo de los bravo,
Guerrero,guerrero,Coyuca de Benitez,coyuca de benitez,
Guerrero,guerrero,El Coacoyul,el coacoyul,
Guerrero,guerrero,Iguala de la Independencia,iguala de la independencia,
Guerrero,guerrero,Ixtapa,ixtapa,
Guerrero,guerrero,La Union,la union,
Guerrero,guerrero,Ometepec,ometepec,
Guerrero,guerrero,Palos Blancos,palos blancos,
Guerrero,guerrero,Petatlán,petatlan,
Guerrero,guerrero,San Jeronimito,san jeronimito,
Guerrero,guerrero,Taxco,taxco,
Guerrero,guerrero,Tecpan de Galeana,tecpan de galeana,
Guerrero,guerrero,Tlapa de Comonfort,tlapa de comonfort,
Guerrero,guerrero,Zihuatanejo de Azueta,zihuatanejo de azueta,
Hidalgo,hidalgo,Acatlán,acatlan,
Hidalgo,hidalgo,Actopan,actopan,
Hidalgo,hidalgo,Agua Blanca Iturbide,agua blanca iturbide,
Hidalgo,hidalgo,Ajacuba,ajacuba,
Hidalgo,hidalgo,Atitalaquia,atitalaquia,
Hidalgo,hidalgo,Cardonal,cardonal,
Hidalgo,hidalgo,Chapulhuacán,chapulhuacan,
Hidalgo,hidalgo,Ciudad Sahagún,ciudad sahagun,
Hidalgo,hidalgo,Cuautepec de Hinojosa,cuautepec de hinojosa,
Hidalgo,hidalgo,Huasca de Ocampo,huasca de ocampo,
Hidalgo,hidalgo,Huejutla,huejutla,
Hidalgo,hidalgo,Ixmiquilpan,ixmiquilpan,
Hidalgo,hidalgo,Jaltepec,jaltepec,
Hidalgo,hidalgo,Pachuca de Soto,pachuca de soto,
Hidalgo,hidalgo,San Felipe Orizatlan,san felipe orizatlan,
Hidalgo,hidalgo,San Juan Hueyapan,san juan hueyapan,
Hidalgo,hidalgo,San Pedro Huaquilpan,san pedro huaquilpan,
Hidalgo,hidalgo,San Salvador el Seco,san salvador,
Hidalgo,hidalgo,Santiago de Anaya,santiago de anaya,
Hidalgo,hidalgo,Santiago Tulantepec,santiago tulantepec,
Hidalgo,hidalgo,Tasquillo,tasquillo,
Hidalgo,hidalgo,Tecozautla,tecozautla,
Hidalgo,hidalgo,Tepeapulco,tepeapulco,
Hidalgo,hidalgo,Tepeji del Río de Ocampo,tepeji del rio de ocampo,
Hidalgo,hidalgo,Tezoquipa,tezoquipa,
Hidalgo,hidalgo,Tizayuca,tizayuca,
Hidalgo,hidalgo,Tlalchiyahualica,tlalchiyahualica,
Hidalgo,hidalgo,Tlaxcoapan,tlaxcoapan,
Hidalgo,hidalgo,Tula de Allende,tula de allende,
Hidalgo,hidalgo,Tulancingo,tulancingo,
Hidalgo,hidalgo,Zacualtipán,zacualtipan,
Hidalgo,hidalgo,Zempoala,zempoala,
Hidalgo,hidalgo,Zimapan,zimapan,
Jalisco,jalisco,Acatic,acatic,
Jalisco,jalisco,Ahualulco de Mercado,ahualulco de mercado,
Jalisco,jalisco,Ajijic,ajijic,
Jalisco,jalisco,Amatitán,amatitan,
Jalisco,jalisco,Ameca,ameca,
Jalisco,jalisco,Arandas,arandas,
Jalisco,jalisco,Atemajac de Brizuela,atemajac de brizuela,
Jalisco,jalisco,Atequiza,atequiza,
Jalisco,jalisco,Atotonilco - Centro Occidente,atotonilco - centro occidente,
Jalisco,jalisco,Atotonilco - Jalisco,atotonilco - jalisco,
Jalisco,jalisco,Atoyac de Álvarez,atoyac,
Jalisco,jalisco,Autlán de Navarro,autlan de navarro,
Jalisco,jalisco,Ayotlán,ayotlan,
Jalisco,jalisco,Ayutla,ayutla,
Jalisco,jalisco,Barra de Navidad,barra de navidad,
Jalisco,jalisco,Bolaños,bolanos,
Jalisco,jalisco,Capilla de Guadalupe,capilla de guadalupe,
Jalisco,jalisco,Careyes,careyes,
Jalisco,jalisco,Casimiro Castillo,casimiro castillo,
Jalisco,jalisco,Castro Urdiales,castro urdiales,
Jalisco,jalisco,Chapala,chapala,
Jalisco,jalisco,Chiquilistlán,chiquilistlan,
Jalisco,jalisco,Cihuatlán,cihuatlan,
Jalisco,jalisco,Ciudad Guzmán,ciudad guzman,
Jalisco,jalisco,Coapinole,coapinole,
Jalisco,jalisco,Cocula,cocula,
Jalisco,jalisco,Colotlán,colotlan,
Jalisco,jalisco,Concepción de Buenos Aires,concepcion de buenos aires,
Jalisco,jalisco,Cuautitlan de Garcia Barragan,cuautitlan de garcia barragan,
Jalisco,jalisco,Cuquio,cuquio,
Jalisco,jalisco,Degollado,degollado,
Jalisco,jalisco,Ejutla,ejutla,
Jalisco,jalisco,El Arenal,el arenal,
Jalisco,jalisco,El Chico,el chico,
Jalisco,jalisco,El Colorado,el colorado,
Jalisco,jalisco,El Grullo,el grullo,
Jalisco,jalisco,El Limón,el limon,
Jalisco,jalisco,El Pitallal,el pitallal,
Jalisco,jalisco,Emiliano Zapata,emiliano zapata,
Jalisco,jalisco,Encarnación de Díaz,encarnacion de diaz,
Jalisco,jalisco,Etzatlán,etzatlan,
Jalisco,jalisco,Guadalajara,guadalajara,
Jalisco,jalisco,Huaxtla,huaxtla,
Jalisco,jalisco,Huejucar,huejucar,
Jalisco,jalisco,Ixtlahuacan de los Membrillos,ixtlahuacan de los membrillos,
Jalisco,jalisco,Ixtlahuacan del Rio,ixtlahuacan del rio,
Jalisco,jalisco,Jalostotitlan,jalostotitlan,
Jalisco,jalisco,Jamay,jamay,
Jalisco,jalisco,Jesus Maria,jesus maria,
Jalisco,jalisco,Jocotepec,jocotepec,
Jalisco,jalisco,Josefino de Allende,josefino de allende,
Jalisco,jalisco,Juanacatlan,juanacatlan,
Jalisco,jalisco,La Barca,la barca,
Jalisco,jalisco,La Huerta,la huerta,
Jalisco,jalisco,La Laja,la laja,
Jalisco,jalisco,La Manzanilla de la Paz,la manzanilla de la paz,
Jalisco,jalisco,La Venta del Astillero,la venta del astillero,
Jalisco,jalisco,Lagos de Moreno,lagos de moreno,
Jalisco,jalisco,Las Juntas,las juntas,
Jalisco,jalisco,Los Ramblases,los ramblases,
Jalisco,jalisco,Magdalena,magdalena,
Jalisco,jalisco,Mascota,mascota,
Jalisco,jalisco,Matatlán,matatlan,
Jalisco,jalisco,Mazamitla,mazamitla,
Jalisco,jalisco,Ocotlan,ocotlan,
Jalisco,jalisco,Ojo Zarco,ojo zarco,
Jalisco,jalisco,Ojuelos,ojuelos,
Jalisco,jalisco,Pihuamo,pihuamo,
Jalisco,jalisco,Poncitlán,poncitlan,
Jalisco,jalisco,Puerto Vallarta,puerto vallarta,
Jalisco,jalisco,Quitupan,quitupan,
Jalisco,jalisco,San Agustin,san agustin,
Jalisco,jalisco,San Andres Ixtlan,san andres ixtlan,
Jalisco,jalisco,San Cristobal de la Barranca,san cristobal de la barranca,
Jalisco,jalisco,San Diego de Alejandria,san diego de alejandria,
Jalisco,jalisco,San Francisco de Asis,san francisco de asis,
Jalisco,jalisco,San Ignacio Cerro Gordo,san ignacio cerro gordo,
Jalisco,jalisco,San Isidro Mazatepec,san isidro mazatepec,
Jalisco,jalisco,San Jose de Gracia,san jose de gracia,
Jalisco,jalisco,San Juan de los Lagos,san juan de los lagos,
Jalisco,jalisco,San Juanito de Escobedo,san juanito de escobedo,
Jalisco,jalisco,San Julian,san julian,
Jalisco,jalisco,San Martin de Bolaños,san martin de bolanos,
Jalisco,jalisco,San Martin Hidalgo,san martin hidalgo,
Jalisco,jalisco,San Miguel el Alto,san miguel el alto,
Jalisco,jalisco,San Patricio,san patricio,
Jalisco,jalisco,San Sebastian del Oeste,san sebastian del oeste,
Jalisco,jalisco,Santa Cruz del Astillero,santa cruz del astillero,
Jalisco,jalisco,Santa Maria del Valle,santa maria del valle,
Jalisco,jalisco,Santiaguito,santiaguito,
Jalisco,jalisco,Sayula,sayula,
Jalisco,jalisco,Tala,tala,
Jalisco,jalisco,Talpa de Allende,talpa de allende,
Jalisco,jalisco,Tamazula,tamazula,
Jalisco,jalisco,Tapalpa,tapalpa,
Jalisco,jalisco,Tecalitlan,tecalitlan,
Jalisco,jalisco,Tecolotlán,tecolotlan,
Jalisco,jalisco,Teocaltiche,teocaltiche,
Jalisco,jalisco,Teocuitatlán de Corona,teocuitatlan de corona,
Jalisco,jalisco,Tepatitlán de Morelos,tepatitlan,
Jalisco,jalisco,Tequesquite,tequesquite,
Jalisco,jalisco,Tequila,tequila,
Jalisco,jalisco,Teuchitlán,teuchitlan,
Jalisco,jalisco,Tlajomulco,tlajomulco,
Jalisco,jalisco,Tlaquepaque,tlaquepaque,
Jalisco,jalisco,Tomatlan,tomatlan,
Jalisco,jalisco,Tonaya,tonaya,
Jalisco,jalisco,Totatiche,totatiche,
Jalisco,jalisco,Tototlan,tototlan,
Jalisco,jalisco,Tuxcacuesco,tuxcacuesco,
Jalisco,jalisco,Tuxpan,tuxpan,
Jalisco,jalisco,Unión de San Antonio,union de san antonio,
Jalisco,jalisco,Unión de Tula,union de tula,
Jalisco,jalisco,Valle de Juarez,valle de juarez,
Jalisco,jalisco,Villa Corona,villa corona,
Jalisco,jalisco,Villa Hidalgo,villa hidalgo,
Jalisco,jalisco,Villa Purificación,villa purificacion,
Jalisco,jalisco,Yahualica de González Gallo,yahualica de gonzalez gallo,
Jalisco,jalisco,Zapopan,zapopan,
Jalisco,jalisco,Zapotiltic,zapotiltic,
Jalisco,jalisco,Zapotlán el Grande,zapotlan el grande,
Jalisco,jalisco,Zapotlanejo,zapotlanejo,
Michoacán,michoacan,Antúnez,antunez,
Michoacán,michoacan,Apatzingán,apatzingan,
Michoacán,michoacan,Aranza,aranza,
Michoacán,michoacan,Caracuaro de Morelos-Centro Occidente,caracuaro de morelos-centro occidente,
Michoacán,michoacan,Caracuaro de Morelos-Centro Sur,caracuaro de morelos-centro sur,
Michoacán,michoacan,Charo,charo,
Michoacán,michoacan,Cheranguerán,cherangueran,
Michoacán,michoacan,Chilchota,chilchota,
Michoacán,michoacan,Churintzio,churintzio,
Michoacán,michoacan,Churumuco,churumuco,
Michoacán,michoacan,Ciudad Hidalgo,ciudad hidalgo,
Michoacán,michoacan,Coahuayana,coahuayana,
Michoacán,michoacan,Coeneo,coeneo,
Michoacán,michoacan,Cotija,cotija,
Michoacán,michoacan,Cucuchucho,cucuchucho,
Michoacán,michoacan,Cuitzeo del Porvenir-Bajío,cuitzeo del porvenir-bajio,
Michoacán,michoacan,Cuitzeo del Porvenir-Centro Occ.,cuitzeo del porvenir- centro occidente,
Michoacán,michoacan,Ecuandureo,ecuandureo,
Michoacán,michoacan,El Tequesquite,el tequesquite,
Michoacán,michoacan,Erongarícuaro,erongaricuaro,
Michoacán,michoacan,Gabriel Zamora,gabriel zamora,
Michoacán,michoacan,Guacamayas,guacamayas,
Michoacán,michoacan,Huetamo,huetamo,
Michoacán,michoacan,Ibarra,ibarra,
Michoacán,michoacan,Jacona,jacona,
Michoacán,michoacan,Jicalan,jicalan,
Michoacán,michoacan,Jiquilpan de Juarez,jiquilpan de juarez,
Michoacán,michoacan,La Piedad,la piedad,
Michoacán,michoacan,La Yerbabuena,la yerbabuena,
Michoacán,michoacan,Lazaro Cardenas,lazaro cardenas,
Michoacán,michoacan,Lombardia,lombardia,
Michoacán,michoacan,Los Nogales,los nogales,
Michoacán,michoacan,Los Reyes de Salgado,los reyes de salgado,
Michoacán,michoacan,Maravatio,maravatio,
Michoacán,michoacan,Mechoacanejo,mechoacanejo,
Michoacán,michoacan,Morelia,morelia,
Michoacán,michoacan,Nocupetaro,nocupetaro,
Michoacán,michoacan,Nueva Italia,nueva italia,
Michoacán,michoacan,Nuevo San Martin,nuevo san martin,
Michoacán,michoacan,Numaran,numaran,
Michoacán,michoacan,Ojo de Rana,ojo de rana,
Michoacán,michoacan,Paracho,paracho,
Michoacán,michoacan,Parácuaro,paracuaro,
Michoacán,michoacan,Pastor Ortiz,pastor ortiz,
Michoacán,michoacan,Patuán,patuan,
Michoacán,michoacan,Pátzcuaro,patzcuaro,
Michoacán,michoacan,Penjamillo,penjamillo,
Michoacán,michoacan,Peribán de Ramos,periban de ramos,
Michoacán,michoacan,Purepero,purepero,
Michoacán,michoacan,Puruandiro,puruandiro,
Michoacán,michoacan,Querendaro,querendaro,
Michoacán,michoacan,Quiroga,quiroga,
Michoacán,michoacan,Rincon Grande,rincon grande,
Michoacán,michoacan,Sahuayo,sahuayo,
Michoacán,michoacan,San Juan de Alima,san juan de alima,
Michoacán,michoacan,San Juanico,san juanico,
Michoacán,michoacan,Santa Clara del Cobre,santa clara del cobre,
Michoacán,michoacan,Tacambaro,tacambaro,
Michoacán,michoacan,Tangamandapio,tangamandapio,
Michoacán,michoacan,Tangancicuaro,tangancicuaro,
Michoacán,michoacan,Tanhuato de Guerrero,tanhuato de guerrero,
Michoacán,michoacan,Tarimbaro,tarimbaro,
Michoacán,michoacan,Tepalcatepec,tepalcatepec,
Michoacán,michoacan,Tingambato,tingambato,
Michoacán,michoacan,Tomendan,tomendan,
Michoacán,michoacan,Turicato,turicato,
Michoacán,michoacan,Tuzantla,tuzantla,
Michoacán,michoacan,Tzintzuntzan,tzintzuntzan,
Michoacán,michoacan,Uruapan,uruapan,
Michoacán,michoacan,Uruétaro,uruetaro,
Michoacán,michoacan,Uspero,uspero,
Michoacán,michoacan,Villa Madero,villa madero,
Michoacán,michoacan,Yurécuaro,yurecuaro,
Michoacán,michoacan,Zacapu,zacapu,
Michoacán,michoacan,Zamora de Hidalgo,zamora de hidalgo,
Michoacán,michoacan,Zinaparo,zinaparo,
Michoacán,michoacan,Zinápecuaro,zinapecuaro,
Michoacán,michoacan,Zitácuaro,zitacuaro,
Morelos,morelos,Axochiapan,axochiapan,
Morelos,morelos,Cuautla,cuautla,
Morelos,morelos,Cuernavaca,cuernavaca,
Morelos,morelos,Jiutepec,jiutepec,
Morelos,morelos,Jojutla,jojutla,
Morelos,morelos,Oaxtepec,oaxtepec,
Morelos,morelos,Temixco,temixco,
Morelos,morelos,Temoac,temoac,
Morelos,morelos,Tepoztlán,tepoztlan,
Morelos,morelos,Tequesquitengo,tequesquitengo,
Morelos,morelos,Ticumán,ticuman,
Morelos,morelos,Xalostoc,xalostoc,
Morelos,morelos,Xochitepec,xochitepec,
Morelos,morelos,Xoxocotla,xoxocotla,
Nayarit,nayarit,Ahuacatlán,ahuacatlan,
Nayarit,nayarit,Amatlán de las Cañas,amtlan de las canas,
Nayarit,nayarit,Bucerías,bucerias,
Nayarit,nayarit,Compostela,compostela,
Nayarit,nayarit,Costa Coral,costa coral,
Nayarit,nayarit,Guayabitos,guayabitos,
Nayarit,nayarit,Higuera Blanca,higuera blanca,
Nayarit,nayarit,Ixtlan del Rio,ixtlan del rio,
Nayarit,nayarit,Jala,jala,
Nayarit,nayarit,La Penita de Jaltemba,la penita de jaltemba,
Nayarit,nayarit,La Yesca,la yesca,
Nayarit,nayarit,Las Jarretaderas,las jarretaderas,
Nayarit,nayarit,Las Varas,las varas,
Nayarit,nayarit,Los Ayala,los ayala,
Nayarit,nayarit,Mezcales,mezcales,
Nayarit,nayarit,Nuevo Vallarta,nuevo vallarta,
Nayarit,nayarit,Punta Mita,punta mita,
Nayarit,nayarit,Ruiz,ruiz,
Nayarit,nayarit,San Blas,san blas,
Nayarit,nayarit,San Francisco,san francisconayarit,
Nayarit,nayarit,San Jose del Valle,san jose del valle,
Nayarit,nayarit,San Juan de Abajo,san juan de abajo,
Nayarit,nayarit,San Pedro Lagunillas,san pedro lagunillas,
Nayarit,nayarit,San Vicente,san vicente,
Nayarit,nayarit,Sayulita,sayulita,
Nayarit,nayarit,Tecuala,tecuala,
Nayarit,nayarit,Tepic,tepic,
Nayarit,nayarit,Valle de Banderas,valle de banderas,
Nayarit,nayarit,Valle Dorado,valle dorado,
Nayarit,nayarit,Xalisco,xalisco,
Nuevo León,nuevo leon,Apodaca,apodaca,
Nuevo León,nuevo leon,Cadereyta Jimenez,cadereyta jimenez,
Nuevo León,nuevo leon,China,china,
Nuevo León,nuevo leon,Ciénega de Flores,cienega de flores,
Nuevo León,nuevo leon,Ciudad Benito Juárez,ciudad benito juarez,
Nuevo León,nuevo leon,Ciudad de Villaldama,ciudad de villaldama,
Nuevo León,nuevo leon,El Carmen,el carmen,
Nuevo León,nuevo leon,Escobedo,escobedo,
Nuevo León,nuevo leon,García de la Cadena,garcia,
Nuevo León,nuevo leon,General Zuazua,general zuazua,
Nuevo León,nuevo leon,Guadalupe,guadalupe,
Nuevo León,nuevo leon,Linares,linares,
Nuevo León,nuevo leon,Montemorelos,montemorelos,
Nuevo León,nuevo leon,Monterrey,monterrey,
Nuevo León,nuevo leon,Pesquería,pesqueria,
Nuevo León,nuevo leon,Sabinas,sabinas hidalgo,
Nuevo León,nuevo leon,Salinas Victoria,salinas victoria,
Nuevo León,nuevo leon,San Nicolas de los Garza,san nicolas de los garza,
Nuevo León,nuevo leon,San Pedro Garza Garcia,san pedro garza garcia,
Nuevo León,nuevo leon,Santa Catarina,santa catarina,
Nuevo León,nuevo leon,Santiago,santiago,
Oaxaca,oaxaca,Asunción Nochixtlán,asuncion nochixtlan,
Oaxaca,oaxaca,Bahías de Huatulco,bahias de huatulco,
Oaxaca,oaxaca,Ciudad Ixtepec,ciudad ixtepec,
Oaxaca,oaxaca,Huajuapan de Leon,huajuapan de leon,
Oaxaca,oaxaca,Jalapa de Diaz,jalapa de diaz,
Oaxaca,oaxaca,Juchitan,juchitan,
Oaxaca,oaxaca,Loma Bonita,loma bonita,
Oaxaca,oaxaca,Maria Lombardo de Caso,maria lombardo de caso,
Oaxaca,oaxaca,Nochixtlan,nochixtlan,
Oaxaca,oaxaca,Oaxaca,oaxaca,
Oaxaca,oaxaca,Puerto Escondido,puerto escondido,
Oaxaca,oaxaca,Salina Cruz,salina cruz,
Oaxaca,oaxaca,San Andres Sinaxtla,san andres sinaxtla,
Oaxaca,oaxaca,San Juan Bautista Tuxtepec,san juan bautista tuxtepec,
Oaxaca,oaxaca,Tehuantepec,tehuantepec,
Oaxaca,oaxaca,Tlaxiaco,tlaxiaco,
Oaxaca,oaxaca,Villa de Tamazulapam del Progreso,villa de tamazulapam del progreso,
Puebla,puebla,Acajete,acajete,
Puebla,puebla,Alchichica,alchichica,
Puebla,puebla,Amozoc,amozoc,
Puebla,puebla,Atlixco,atlixco,
Puebla,puebla,Chipilo de Francisco Javier Mina,chipilo de francisco javier mina,
Puebla,puebla,Cholula,cholula,
Puebla,puebla,Ciudad Serdán,ciudad serdan,
Puebla,puebla,Cuautlancingo,cuautlancingo,
Puebla,puebla,Cuyoaco,cuyoaco,
Puebla,puebla,Hueytamalco,hueytamalco,
Puebla,puebla,Izucar de Matamoros,izucar de matamoros,
Puebla,puebla,Puebla,puebla,
Puebla,puebla,San Jose Chiapa,san jose chiapa,
Puebla,puebla,San Martin Texmelucan,san martin texmelucan,
Puebla,puebla,San Salvador,san salvador el seco,
Puebla,puebla,Santa Rita Tlahuapan,santa rita tlahuapan,
Puebla,puebla,Tehuacán,tehuacan,
Puebla,puebla,Tepatlaxco de Hidalgo,tepatlaxco de hidalgo,
Puebla,puebla,Tepeaca,tepeaca,
Puebla,puebla,Teziutlán,teziutlan,
Puebla,puebla,Xicotépec de Juárez,xicotepec de juarez,
Puebla,puebla,Zacapoaxtla,zacapoaxtla,
Querétaro,queretaro,Amealco,amealco,
Querétaro,queretaro,Cadereyta de Montes,cadereyta de montes,
Querétaro,queretaro,El Marqués,el marques,
Querétaro,queretaro,Ezequiel Montes,ezequiel montes,
Querétaro,queretaro,Huimilpan,huimilpan,
Querétaro,queretaro,Jalpan de Serra,jalpan de serra,
Querétaro,queretaro,Juriquilla,juriquilla,
Querétaro,queretaro,Landa de Matamoros,landa de matamoros,
Querétaro,queretaro,Maconi,maconi,
Querétaro,queretaro,Queretaro,queretaro,
Querétaro,queretaro,Tequisquiapan,tequisquiapan,
Quintana Roo,quintana roo,Bacalar,bacalar,
Quintana Roo,quintana roo,Benito Juárez,benito juarez,
Quintana Roo,quintana roo,Cancún,cancun,
Quintana Roo,quintana roo,Chetumal,chetumal,
Quintana Roo,quintana roo,Cozumel,cozumel,
Quintana Roo,quintana roo,Felipe Carrillo Puerto,felipe carrillo puerto,
Quintana Roo,quintana roo,Islas Mujeres,islas mujeres,
Quintana Roo,quintana roo,Jose Maria Morelos,jose maria morelos,
Quintana Roo,quintana roo,Othon P. Blanco,othon p. blanco,
Quintana Roo,quintana roo,Playa del Carmen,playa del carmen,
Quintana Roo,quintana roo,Puerto Morelos,puerto morelos,
Quintana Roo,quintana roo,Solidaridad,solidaridad,
Quintana Roo,quintana roo,Tulum,tulum,
Quintana Roo,quintana roo,X-Hazil Sur,x-hazil sur,
San Luis Potosí,san luis potosi,Alaquines,alaquines,
San Luis Potosí,san luis potosi,Axtla de Terrazas,axtla de terrazas,
San Luis Potosí,san luis potosi,Ciudad del Maíz,ciudad del maiz,
San Luis Potosí,san luis potosi,Ciudad Fernández,ciudad fernandez,
San Luis Potosí,san luis potosi,Ciudad Valles,ciudad valles,
San Luis Potosí,san luis potosi,Ebano,ebano,
San Luis Potosí,san luis potosi,El Naranjo,el naranjo,
San Luis Potosí,san luis potosi,La Hincada,la hincada,
San Luis Potosí,san luis potosi,Lagunillas,lagunillas,
San Luis Potosí,san luis potosi,Las Golondrinas Santo Domingo,las golondrinas santo domingo,
San Luis Potosí,san luis potosi,Matehuala,matehuala,
San Luis Potosí,san luis potosi,Matlapa,matlapa,
San Luis Potosí,san luis potosi,Rioverde,rioverde,
San Luis Potosí,san luis potosi,San Luis Potosí,san luis potosi,
San Luis Potosí,san luis potosi,San Martin Chalchicuautla,san martin chalchicuautla,
San Luis Potosí,san luis potosi,Tamasopo,tamasopo,
San Luis Potosí,san luis potosi,Tamazunchale,tamazunchale,
San Luis Potosí,san luis potosi,Tampacan,tampacan,
San Luis Potosí,san luis potosi,Tamuin,tamuin,
San Luis Potosí,san luis potosi,Tancanhuitz,tancanhuitz,
San Luis Potosí,san luis potosi,Xilitla,xilitla,
Sinaloa,sinaloa,Ahome,ahome,
Sinaloa,sinaloa,Angostura,angostura,
Sinaloa,sinaloa,Badiraguato,badiraguato,
Sinaloa,sinaloa,Choix,choix,
Sinaloa,sinaloa,Concordia,concordia,
Sinaloa,sinaloa,Cosala,cosala,
Sinaloa,sinaloa,Culiacan,culiacan,
Sinaloa,sinaloa,El Dorado,el dorado,
Sinaloa,sinaloa,El Fuerte,el fuerte,
Sinaloa,sinaloa,Elota,elota,
Sinaloa,sinaloa,Escuinapa,escuinapa,
Sinaloa,sinaloa,Guamúchil,guamuchil,
Sinaloa,sinaloa,Guasave,guasave,
Sinaloa,sinaloa,Los Mochis,los mochis,
Sinaloa,sinaloa,Mazatlán,mazatlan,
Sinaloa,sinaloa,Mocorito,mocorito,
Sinaloa,sinaloa,Navolato,navolato,
Sinaloa,sinaloa,Pericos,pericos,
Sinaloa,sinaloa,Rosario,rosario,
Sinaloa,sinaloa,Salvador Alvarado,salvador alvarado,
Sinaloa,sinaloa,San Ignacio,san ignacio,
Sonora,sonora,Agua Prieta,agua prieta,
Sonora,sonora,Álamos,alamos,
Sonora,sonora,Altar,altar,
Sonora,sonora,Bacoachi,bacoachi,
Sonora,sonora,Bacobampo,bacobampo,
Sonora,sonora,Bacúm,bacum,
Sonora,sonora,Caborca,caborca,
Sonora,sonora,Cananea,cananea,
Sonora,sonora,Ciudad Obregón,ciudad obregon,
Sonora,sonora,Cucurpe,cucurpe,
Sonora,sonora,Empalme,empalme,
Sonora,sonora,Esperanza,esperanza,
Sonora,sonora,Guaymas,guaymas,
Sonora,sonora,Hermosillo,hermosillo,
Sonora,sonora,Huatabampo,huatabampo,
Sonora,sonora,Imuris,imuris,
Sonora,sonora,La Victoria,la victoria,
Sonora,sonora,Magdalena de Kino,magdalena de kino,
Sonora,sonora,Nacozari de Garcia,nacozari de garcia,
Sonora,sonora,Navojoa,navojoa,
Sonora,sonora,Nogales,nogales,
Sonora,sonora,Pitiquito,pitiquito,
Sonora,sonora,Potam,potam,
Sonora,sonora,Pueblo Yaqui,pueblo yaqui,
Sonora,sonora,Puerto Peñasco,puerto penasco,
Sonora,sonora,Quetchehueca,quetchehueca,
Sonora,sonora,Sahuaripa,sahuaripa,
Sonora,sonora,San Carlos,san carlos,
Sonora,sonora,San Ignacio Rio Muerto,san ignacio rio muerto,
Sonora,sonora,San Luis Rio Colorado,san luis rio colorado,
Sonora,sonora,San Pedro de la Cueva,san pedro de la cueva,
Sonora,sonora,Santa Ana Pacueco,santa ana,
Sonora,sonora,Sonoyta,sonoyta,
Sonora,sonora,Vicam,vicam,
Sonora,sonora,Villa Juárez,villa juarez,
Tabasco,tabasco,Balancán,balancan,
Tabasco,tabasco,Cárdenas,cardenas,
Tabasco,tabasco,Centla,centla,
Tabasco,tabasco,Comalcalco,comalcalco,
Tabasco,tabasco,Cunduacan,cunduacan,
Tabasco,tabasco,Huimanguillo,huimanguillo,
Tabasco,tabasco,Jalpa,jalpa de mendez,
Tabasco,tabasco,Macuspana,macuspana,
Tabasco,tabasco,Nacajuca,nacajuca,
Tabasco,tabasco,Paraíso,paraiso,
Tabasco,tabasco,Teapa,teapa,
Tabasco,tabasco,Tenosique,tenosique,
Tabasco,tabasco,Villahermosa,villahermosa,
Tamaulipas,tamaulipas,Altamira,altamira,
Tamaulipas,tamaulipas,Ciudad Camargo,ciudad camargo,
Tamaulipas,tamaulipas,Ciudad de Mier,ciudad de mier,
Tamaulipas,tamaulipas,Ciudad Madero,ciudad madero,
Tamaulipas,tamaulipas,Ciudad Mante,ciudad mante,
Tamaulipas,tamaulipas,Ciudad Victoria,ciudad victoria,
Tamaulipas,tamaulipas,Miguel Alemán,miguel aleman,
Tamaulipas,tamaulipas,Nuevo Laredo,nuevo laredo,
Tamaulipas,tamaulipas,Nuevo Progreso,nuevo progreso,
Tamaulipas,tamaulipas,Reynosa,reynosa,
Tamaulipas,tamaulipas,Rio Bravo,rio bravo,
Tamaulipas,tamaulipas,Soto la Marina,soto la marina,
Tamaulipas,tamaulipas,Tampico Alto,tampico,
Tamaulipas,tamaulipas,Valle Hermoso,valle hermoso,
Tamaulipas,tamaulipas,Xicoténcatl,xicotencatl,
Tlaxcala,tlaxcala,Apizaco,apizaco,
Tlaxcala,tlaxcala,Tlaxcala,tlaxcala,
Tlaxcala,tlaxcala,Tlaxco,tlaxco,
Veracruz,veracruz,Acayucan,acayucan,
Veracruz,veracruz,Acula,acula,
Veracruz,veracruz,Acultzingo,acultzingo,
Veracruz,veracruz,Álamo,alamo,
Veracruz,veracruz,Alto Lucero de Gutiérrez Barrios,alto lucero de gutierrez barrios,
Veracruz,veracruz,Altotonga,altotonga,
Veracruz,veracruz,Alvarado,alvarado,
Veracruz,veracruz,Amatitlán,amatitlan,
Veracruz,veracruz,Ángel R. Cabada,angel r. cabada,
Veracruz,veracruz,Antón Lizardo,anton lizardo,
Veracruz,veracruz,Apazapan,apazapan,
Veracruz,veracruz,Boca del Río,boca del rio,
Veracruz,veracruz,Camarón de Tejeda,camaron de tejeda,
Veracruz,veracruz,Catemaco,catemaco,
Veracruz,veracruz,Chalma,chalma,
Veracruz,veracruz,Chicontepec,chicontepec,
Veracruz,veracruz,Coahuitlán,coahuitlan,
Veracruz,veracruz,Coatepec,coatepec,
Veracruz,veracruz,Coatzacoalcos,coatzacoalcos,
Veracruz,veracruz,Córdoba,cordoba,
Veracruz,veracruz,Cosamaloapan,cosamaloapan,
Veracruz,veracruz,Cotaxtla,cotaxtla,
Veracruz,veracruz,Coyutla,coyutla,
Veracruz,veracruz,Cuitlahuac,cuitlahuac,
Veracruz,veracruz,Dos Rios,dos rios,
Veracruz,veracruz,Espinal,espinal,
Veracruz,veracruz,Fortín,fortin,
Veracruz,veracruz,Huatusco,huatusco,
Veracruz,veracruz,Huayacocotla,huayacocotla,
Veracruz,veracruz,Hueyapan de Ocampo,hueyapan de ocampo,
Veracruz,veracruz,Isla,isla,
Veracruz,veracruz,Jose Cardel,jose cardel,
Veracruz,veracruz,Las Choapas,las choapas,
Veracruz,veracruz,Lerdo de Tejada,lerdo de tejada,
Veracruz,veracruz,Martinez de la Torre,martinez de la torre,
Veracruz,veracruz,Medellín,medellin,
Veracruz,veracruz,Minatitlán,minatitlan,
Veracruz,veracruz,Misantla,misantla,
Veracruz,veracruz,Nanchital,nanchital,
Veracruz,veracruz,Oluta,oluta,
Veracruz,veracruz,Orizaba,orizaba,
Veracruz,veracruz,Ozuluama de Mascareñas,ozuluama de mascarenas,
Veracruz,veracruz,Pánuco,panuco,
Veracruz,veracruz,Papantla,papantla,
Veracruz,veracruz,Perote,perote,
Veracruz,veracruz,Playa Vicente,playa vicente,
Veracruz,veracruz,Potrero del Llano,potrero del llano,
Veracruz,veracruz,Poza Rica de Hidalgo,poza rica de hidalgo,
Veracruz,veracruz,Rinconada,rinconada,
Veracruz,veracruz,San Andres Tuxtla,san andres tuxtla,
Veracruz,veracruz,Tampico,tampico alto,
Veracruz,veracruz,Tantoyuca,tantoyuca,
Veracruz,veracruz,Tecolutla,tecolutla,
Veracruz,veracruz,Tempoal,tempoal,
Veracruz,veracruz,Tepetzingo,tepetzingo,
Veracruz,veracruz,Tierra Blanca,tierra blanca,
Veracruz,veracruz,Tihuatlán,tihuatlan,
Veracruz,veracruz,Tlacotalpan,tlacotalpan,
Veracruz,veracruz,Tlaltetela,tlaltetela,
Veracruz,veracruz,Tlapacoyan,tlapacoyan,
Veracruz,veracruz,Tres Valles,tres valles,
Veracruz,veracruz,Veracruz,veracruz,
Veracruz,veracruz,Villa Cuauhtémoc,villa cuauhtemoc,
Veracruz,veracruz,Xalapa,xalapa,
Yucatán,yucatan,Buctzotz,buctzotz,
Yucatán,yucatan,Caucel,caucel,
Yucatán,yucatan,Celestún,celestun,
Yucatán,yucatan,Conkal,conkal,
Yucatán,yucatan,Dzemul,dzemul,
Yucatán,yucatan,Dzidzantun,dzidzantun,
Yucatán,yucatan,Dzilam Gonzalez,dzilam gonzalez,
Yucatán,yucatan,Izamal,izamal,
Yucatán,yucatan,Mani,mani,
Yucatán,yucatan,Mérida,merida,
Yucatán,yucatan,Motul,motul,
Yucatán,yucatan,Muna,muna,
Yucatán,yucatan,Popola,popola,
Yucatán,yucatan,Progreso,progeso,
Yucatán,yucatan,San Pedro Noh Pat,san pedro noh pat,
Yucatán,yucatan,Sisal,sisal,
Yucatán,yucatan,Tamchen,tamchen,
Yucatán,yucatan,Tekax,tekax,
Yucatán,yucatan,Tekit,tekit,
Yucatán,yucatan,Ticul,ticul,
Yucatán,yucatan,Tinum,tinum,
Yucatán,yucatan,Tizimín,tizimin,
Yucatán,yucatan,Uman,uman,
Yucatán,yucatan,Valladolid,valladolid,
Zacatecas,zacatecas,Agua Dulce,agua dulce,
Zacatecas,zacatecas,Apulco,apulco,
Zacatecas,zacatecas,Concepción del Oro,concepcion del oro,
Zacatecas,zacatecas,Fresnillo,fresnillo,
Zacatecas,zacatecas,García,garcia de la cadena,
Zacatecas,zacatecas,Jalpa de Mendez,jalpa,
Zacatecas,zacatecas,Momax,momax,
Zacatecas,zacatecas,Monte Escobedo,monte escobedo,
Zacatecas,zacatecas,Rio Florido,rio florido,
Zacatecas,zacatecas,Sombrerete,sombrerete,
Zacatecas,zacatecas,Tepechitlán,tepechitlan,
Zacatecas,zacatecas,Tepetongo,tepetongo,
Zacatecas,zacatecas,Tlaltenango de Sanchez Roman,tlaltenango de sanchez roman,
Zacatecas,zacatecas,Zacatecas,zacatecas,
`;